<?php

function demo_schema()
{
	$schema['demo'] = array(
	  'description' => 'Demo table',
	  'fields' => array(
	    'col1' => array(
			'description' => 'make col1 primary key auto increment',
			'type' => 'serial',
			'size' => 'big',
			'not null' => TRUE,
			'unsigned' => TRUE,
	    ),
	    'col2' => array(
			'description' => 'A column',
			'type' => 'int',
			'default' => 0,
			'not null' => TRUE,
	    ),
	  ),
	  'primary key' => array('col1'),
	);

	return $schema;
}
